receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s
  filter:
    spans:
      exclude:
        match_type: strict
        span_names:
          - /swagger/*any

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    loglevel: info

service:
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ batch, filter ]
        exporters: [ jaeger, logging ]